postgres:
  ports:
    - '5432:5432'
  restart: always
  image: postgres:10.5
  environment:
    POSTGRES_USER: pgadmin
    POSTGRES_PASSWORD: pgadmin
    POSTGRES_DB: apiblog

redis:
  image: redis
  ports:
    - '6379:6379'